version: '3.8'
services:
    # PHP - Phalcon
    php-phalcon-environment:
        container_name: php-phalcon
        build:
            context: ./php-phalcon
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./php-phalcon/src:/var/www/html
        ports:
            - '8000:80'
        expose:
            - '8000'
        depends_on:
            - db
        links:
            - db
    
    # PHP - Apache
    #php-apache-environment:
    #    container_name: php-apache
    #    build:
    #        context: ./php
    #        dockerfile: Dockerfile
    #    depends_on:
    #        - db
    #    volumes:
    #        - ./php/src:/var/www/html/
    #    ports:
    #        - 8000:80

    # Database
    db:
        container_name: mysql
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: ERP
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - '9906:3306'
            
        # Bind data (like mounted volume)
        volumes:
            - type: bind
              source: ./bind/mysqldata
              target: /var/lib/mysql

        # Init the db
        #volumes:
        #    - ./sql:/docker-entrypoint-initdb.d

        # Copy data in volume
        #volumes:
        #    - type: volume
        #      source: mysqldata
        #      target: /var/lib/mysql

        # Copy data in mounted volume
        #volumes:
            #- ./volume/mysqldata:/var/lib/mysql

            #- type: volume
            #  source: ./volume/mysqldata
            #  target: /var/lib/mysql
            #  volume:
            #    nocopy: true

        # Data
            #- type: volume
            #  source: mysqldata
            #  target: /var/lib/mysql
            #  volume:
            #    nocopy: true
            #- type: bind
            #  source: ./static
            #  target: /opt/app/static

    # Database editor
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
# For volumes
#volumes:
#    mysqldata:
#        name: mysqldata
#        #external: true